<script>
    //Task 1
    function a([first,second,third,...rest]){
        return {first,second,third,rest}
    }
    
    //Task 2
    //Task 3
    //a
    function abc(arr1,arr2){
        return [...arr1,...arr2]
    }
    //b
    function addKeyVal(a, b, c){
        a[b] = c;
    }
    //c
    function removeKey(obj, key) {
        delete obj[key] ;
    }
    //d
    function combine(obj1,obj2){
        return {
            ...obj1,...obj2
        }
    }
    //e
    function update(obj,k,v){
        obj[k] = v 
    }
    update(person,'semester',7)
    //f
    //Task 4
    function delay(ms) {
        return new Promise(resolve => setTimeout(resolve, ms));
      }
      
      delay(3000).then(() => alert('runs after 3 seconds'));
    //Task 5
    async function loadJson(url) { // (1)
        let response = await fetch(url); // (2)
      
        if (response.status == 200) {
          let json = await response.json(); // (3)
          return json;
        }
      
        throw new Error(response.status);
      }
      
      loadJson('no-such-user.json').catch(alert); // Error: 404 (4)
      //TAsk6
      class HttpError extends Error {
        constructor(response) {
          super(`${response.status} for ${response.url}`);
          this.name = 'HttpError';
          this.response = response;
        }
      }
      
      async function loadJson(url) {
        let response = await fetch(url);
        if (response.status == 200) {
          return response.json();
        } else {
          throw new HttpError(response);
        }
      }
      
      // Ask for a user name until github returns a valid user
      async function demoGithubUser() {
      
        let user;
        while(true) {
          let name = prompt("Enter a name?", "iliakan");
      
          try {
            user = await loadJson(`https://api.github.com/users/${name}`);
            break; // no error, exit loop
          } catch(err) {
            if (err instanceof HttpError && err.response.status == 404) {
              // loop continues after the alert
              alert("No such user, please reenter.");
            } else {
              // unknown error, rethrow
              throw err;
            }
          }
        }
        alert(`Full name: ${user.name}.`);
        return user;
      }
      demoGithubUser();
      //Task 7
      async function wait() {
        await new Promise(resolve => setTimeout(resolve, 1000));
      
        return 10;
      }
      function f() {
        // shows 10 after 1 second
        wait().then(result => alert(result));
      }
      f();
      //Task 9
      function logOne () {
          return new Promise(resolve=>{
            setTimeout(function () {
              resolve();
              console.log("one!");
             }, Math.random() * 1000);
           })
         }
        
         function logTwo () {
           return new Promise(resolve=>{
             setTimeout(function () {
               resolve();
               console.log("two!");
             }, Math.random() * 1000);
           })
         }
        
         async function inOrder(logOne,logTwo){
           const result = await logOne();
           const result1 = await logTwo();
         }
        
         inOrder(logOne,logTwo);
    </script>